CREATE TABLE Users (
 Id INT IDENTITY (1,1) PRIMARY KEY
,AspNetUserId NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id) NOT NULL
,IsActive BIT DEFAULT 1 NOT NULL
,UserName VARCHAR(200) NOT NULL
,DefaultPrivate BIT DEFAULT 0 NOT NULL
)


CREATE TABLE Realms (
 Id INT IDENTITY (1,1) PRIMARY KEY
,IsActive BIT DEFAULT 1 NOT NULL
,[Name] VARCHAR(200) NOT NULL
)

CREATE TABLE UserRealms (
 Id INT IDENTITY (1,1) PRIMARY KEY
,RealmId INT FOREIGN KEY REFERENCES Realms(Id) NOT NULL
,UserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
,Created DATETIME NOT NULL
)

CREATE TABLE Locations (
 Id INT IDENTITY (1,1) PRIMARY KEY
,IsActive BIT DEFAULT 1 NOT NULL
,[Name] VARCHAR (400) NOT NULL
,RealmId INT FOREIGN KEY REFERENCES Realms(Id) NOT NULL
,CreatedAt DATETIME NOT NULL
,CreatedBy INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
,Modified DATETIME 
,ModifiedBy INT FOREIGN KEY REFERENCES Users(Id) 
)

CREATE TABLE Items (
 Id INT IDENTITY (1,1) PRIMARY KEY
,LocationId INT FOREIGN KEY REFERENCES Locations(ID) NOT NULL
,[Name] VARCHAR (400) NOT NULL
,CreatedAt DATETIME NOT NULL
,CreatedBy INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
,Modified DATETIME 
,ModifiedBy INT FOREIGN KEY REFERENCES Users(Id) 
)

CREATE TABLE TransactionTypes(
 Id INT IDENTITY (1,1) PRIMARY KEY
,[Transaction] VARCHAR(15) NOT NULL
)

INSERT INTO TransactionTypes ([Transaction])
VALUES
('Placed'),
('Removed')

CREATE TABLE Trasactions (
 Id INT IDENTITY (1,1) PRIMARY KEY
,TransactionTime DATETIME NOT NULL
,UserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
,ItemId INT FOREIGN KEY REFERENCES Items(Id) NOT NULL
,LocationId INT FOREIGN KEY REFERENCES Locations(Id) NOT NULL
 )



